version: "3.4"

networks:
  dev:
    driver: bridge

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    depends_on:
      - "homemade_goodies"
    container_name: hg-services
    ports:
      - "8088:443"
      - "3033:80"
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ConnectionStrings__LiveDbString=Host=${DB_HOST};Database=${DB_DATABASE};Username=${DB_USERNAME};Password=${DB_PASSWORD}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8088
      - ASPNETCORE_HTTP_PORT=3033
    networks:
      - dev

  homemade_goodies:
    image: postgres:latest
    container_name: homemade_goodies
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "5432"
    restart: always
    volumes:
      - homemade_goodies:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  homemade_goodies:
